imu0: /android/imu
imu0_config: [
              # false, false, false,
              # false, false, true,
              # false, false, false,
              # false, false, true,
              # true,  false, false
              false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              true,  true, true
             ]
imu0_queue_size: 10
imu0_nodelay: false
imu0_differential: false
imu0_relative: true
imu0_remove_gravitational_acceleration: true
